apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinite-calls
  labels:
    app: infinite-calls
spec:
  replicas: 10
  containers:
      - name: infinite-calls
        image: kritid9/load-testing:v1
